### ISSUE TITLE
Verify a webhook's authenticity

### ISSUE THREAD

**Issue by raulpopadineti** [paymoapp/api#32]
Currently there's no way to check the authenticity of an event received from your API. There are a few approaches that are quite easy to add in:
1. http://resthooks.org/docs/security/
2. https://developers.trello.com/page/webhooks#section-webhook-signatures

Can you tell me if this is something you're taking into consideration in the near future?

Thanks!

**Comment by urkle** [comment]
Another good example of this is Github..  https://developer.github.com/v3/repos/hooks/#create-a-hook

They simply allow you to specify a secret when creating or updating a webhook (but NOT retrieving it when fetching a webhook details).

This provides a clean way to verify that the webhook was in fact sent by Paymo and not someone else.  Otherwise we can't 100% trust the payload. 

This should be a very simple thing to add to the API and improve the quality and trust worthiness of the Paymo API overall.

**Comment by paymo-old** [comment]
We've added webhook signatures: https://github.com/paymoapp/api/blob/master/sections/webhooks.md#signature

**Comment by raulpopadineti** [comment]
Thanks a lot @paymoapp! 🎉 🍻
